import type { Metadata } from "next"
import { ReduxProvider } from "@/providers/redux-provider"

import { SocketProvider } from "@/providers/socket-provider"
import { RouteGuard } from "@/components/layout/resource-guard"
import { AuthProvider } from "@/providers/auth-provider"
import { AppLayoutProvider } from "@/providers/app-layout-provider"
import { AccountModalProvider } from "@/contexts/account-modal.context"

import "@/styles/index.scss"
import { NON_GUARD_ROUTES } from "@/configs/layout"
import { Toaster } from "@/components/materials/sonner"
import { ErrorIconForToast } from "@/components/layout/icons"
import { SuccessIconForToast } from "@/components/layout/icons"
import { GlobalCallManager } from "@/components/voice-call/global-call-manager"
import { NotificationBadgeProvider } from "@/providers/notification-badge-provider"
import VoiceAssistantWeb from "@/components/voice-assistant/voice-assistant"
import { UserSettingsProvider } from "@/providers/user-settings-provider"

export const metadata: Metadata = {
  title: "Thunder Chat",
  description: "Generated by Code VCN",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/public/favicon.ico" />
      </head>
      <body className="bg-white text-white">
        <ReduxProvider>
          <AuthProvider>
            <UserSettingsProvider>
              <RouteGuard nonGuardRoutes={NON_GUARD_ROUTES}>
                <SocketProvider>
                  <AppLayoutProvider>
                    <AccountModalProvider>
                      <NotificationBadgeProvider>
                        <GlobalCallManager>{children}</GlobalCallManager>
                        <VoiceAssistantWeb />
                      </NotificationBadgeProvider>
                    </AccountModalProvider>
                  </AppLayoutProvider>
                </SocketProvider>
              </RouteGuard>
            </UserSettingsProvider>
          </AuthProvider>
        </ReduxProvider>
        <Toaster
          position="bottom-right"
          richColors
          closeButton
          theme="light"
          duration={3000}
          icons={{
            success: <SuccessIconForToast />,
            error: <ErrorIconForToast />,
          }}
        />
      </body>
    </html>
  )
}
